apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres-service","namespace":"default"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"postgres"}}}
  creationTimestamp: "2025-07-01T14:27:35Z"
  name: postgres-service
  namespace: default
  resourceVersion: "2524401"
  uid: 310fe452-e710-4dae-bca5-928917bae64b
spec:
  clusterIP: 10.97.146.230
  clusterIPs:
  - 10.97.146.230
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
