########################################################################
# 1) Secret – holds credentials (editable in plain‑text for clarity)
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER:   admin
  POSTGRES_PASSWORD: hajox245
  POSTGRES_DB:     todo
---
########################################################################
# 2) ConfigMap – PostgreSQL and pg_hba configs
########################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    # Basic settings
    port               = 5432
    listen_addresses   = '*'
    max_connections    = 100
    shared_buffers     = 128MB

    # WAL / replication demo (optional)
    wal_level          = replica
    archive_mode       = on
    archive_command    = 'test ! -f /data/archive/%f && cp %p /data/archive/%f'
    max_wal_senders    = 3
    min_wal_size       = 80MB
    max_wal_size       = 1GB
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS         METHOD
    local   all             all                             trust
    host    all             all             0.0.0.0/0       md5
    host    all             all             ::/0            md5
---
########################################################################
# 3) StatefulSet – main Postgres workload (+ per‑pod PVC)
########################################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres          # must match Service metadata.name
  replicas: 1                    # one primary
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: postgres:15                      # pick your tag
          args: ["-c", "config_file=/config/postgresql.conf"]
          env:
            - name: PGDATA
              value: "/data/pgdata"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: postgres-config
            defaultMode: 0444
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard      # change if your cluster uses another class
        resources:
          requests:
            storage: 5Gi                # adjust capacity
---
########################################################################
# 4) Headless Service – stable DNS for the StatefulSet
########################################################################
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: None                      # headless
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
