name: PSQL on Kubernetes

on: [push]

jobs:
  psql-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

    - name: Run psql inside pod
      run: |
        kubectl exec -i postgres-77b9f6756-jm747 -- \
          env PGPASSWORD=your_password \
          psql -h localhost -U admin -p 5432 -d todo -c '\l'
