name: PostgreSQL Connection Check

on:
  workflow_dispatch:

jobs:
  check-postgres:
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Wait for PostgreSQL pod to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=postgresins --timeout=90s

      - name: Get pod name
        id: pod
        run: |
          echo "POD_NAME=$(kubectl get pods -l app=postgres -o jsonpath='{.items[0].metadata.name}')" >> $GITHUB_ENV

      - name: Check DB connection
        run: |
          kubectl exec -i $POD_NAME -- \
          psql -U ps_user -d ps_db -c "SELECT 1;"
